version: '3.8'

services:
  airflow-standalone:
    image: apache/airflow:2.7.3-python3.10
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=false
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=true
      - _PIP_ADDITIONAL_REQUIREMENTS=pandas nltk pymongo
      - MONGO_HOST=kafkaproject-mongodb-1
      - MONGO_PORT=27017
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ../preprocessing:/opt/airflow/preprocessing
      - "./kafka_project:/opt/airflow/kafka_project"
    command: bash -c "airflow db init && airflow users create --username airflow --password airflow --firstname Admin --lastname User --role Admin --email admin@example.com && airflow standalone"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - kafkaproject_default

networks:
  kafkaproject_default:
    external: true
